### ISSUE TITLE
implement a delay for page loading in when tracing GitLab pages

### ISSUE THREAD

**Issue by talyacooper** [lanl/trace-crawler#2]
When a user created a json trace of the "All" tab on a GitLab issues pages, "Open issues" automatically loaded first, before the browser clicked the "All" issues tab. This caused Selenium to only react to the first load (on the open issues tab) and thus not to crawl the links on the second load (on the all issues tab). Adding 3 sec between events fixed the issue. 

The problem only occurred on GitLab pages with a very small number of open issues, as the lag time it takes to load a larger number of open issues gives the browser time to click the "All" tab.

**Comment by luda171** [comment]
commited change
