### ISSUE TITLE
gitlab "next" button results in a loop on the final page of merge results

### ISSUE THREAD

**Issue by talyacooper** [lanl/trace-crawler#3]
The crawler gets stuck in a loop on the final page of GitLab merge requests, due to an issue with how the "next" button is coded. 
The next button in “merged” issues does have a default “disable attribute,” but the parent element has class “disabled”.
This creates a loop because there is no exit condition for the crawler. Moreover, Selenium cannot detect that button is disabled.

**Comment by luda171** [comment]
fixed by  exiting   if parent  has "disabled" class attribute.
